blueprint:
  name: Allumer lumière extérieure à ouverture porte garage (conditions soleil paramétrables)
  description: >
    Allume une lumière extérieure à l'ouverture de la porte de garage,
    uniquement selon les conditions de lever/coucher du soleil définies par l'utilisateur,
    puis l'éteint après un délai.
  domain: automation
  input:
    door_sensor:
      name: Capteur de porte garage
      description: Sélectionnez le capteur de contact de la porte de garage
      selector:
        entity:
          domain: binary_sensor
    target_light:
      name: Lumière extérieure
      description: Sélectionnez la lumière à contrôler
      selector:
        entity:
          domain: light
    delay_minutes:
      name: Durée avant extinction
      description: Nombre de minutes avant que la lumière s’éteigne
      default: 2
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          mode: slider
    enable_after_sunset:
      name: Activer après coucher du soleil
      description: Active la condition "après le coucher du soleil"
      default: true
      selector:
        boolean:
    sunset_offset:
      name: Décalage coucher du soleil (minutes)
      description: Décalage par rapport au coucher du soleil (négatif = avant, positif = après)
      default: -15
      selector:
        number:
          min: -120
          max: 120
          step: 1
          unit_of_measurement: minutes
    enable_before_sunrise:
      name: Activer avant lever du soleil
      description: Active la condition "avant le lever du soleil"
      default: true
      selector:
        boolean:
    sunrise_offset:
      name: Décalage lever du soleil (minutes)
      description: Décalage par rapport au lever du soleil (négatif = avant, positif = après)
      default: 15
      selector:
        number:
          min: -120
          max: 120
          step: 1
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: "on"

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {% if (enable_after_sunset | default(true)) %}
          {{ now() >= state_attr('sun.sun', 'next_setting') | as_datetime + timedelta(minutes=sunset_offset | int) }}
          {% else %} false {% endif %}
      - condition: template
        value_template: >
          {% if (enable_before_sunrise | default(true)) %}
          {{ now() <= state_attr('sun.sun', 'next_rising') | as_datetime + timedelta(minutes=sunrise_offset | int) }}
          {% else %} false {% endif %}

action:
  - service: light.turn_on
    target:
      entity_id: !input target_light
  - delay:
      minutes: !input delay_minutes
  - service: light.turn_off
    target:
      entity_id: !input target_light

mode: restart
