blueprint:
  name: Allumer interrupteur extérieur à ouverture porte garage (nuit)
  description: >
    Allume un interrupteur (lumière extérieure) quand la porte de garage s'ouvre,
    uniquement dans la plage 15 min avant coucher du soleil → 15 min après lever du soleil,
    puis éteint après un délai.
  domain: automation
  input:
    door_sensor:
      name: Capteur de porte garage
      description: Sélectionnez le capteur de contact de la porte de garage
      selector:
        entity:
          domain: binary_sensor
    target_switch:
      name: Interrupteur extérieur
      description: Sélectionnez l'interrupteur à contrôler
      selector:
        entity:
          domain: switch
    delay_minutes:
      name: Durée avant extinction
      description: Nombre de minutes avant que l'interrupteur s’éteigne
      default: 2
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider

trigger:
  - platform: state
    entity_id: !input door_sensor
    to: "on"

condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:15:00"
      - condition: sun
        before: sunrise
        before_offset: "00:15:00"

action:
  - service: switch.turn_on
    target:
      entity_id: !input target_switch
  - delay:
      minutes: !input delay_minutes
  - service: switch.turn_off
    target:
      entity_id: !input target_switch

mode: restart
